/* Supabase Edge Function — audit-worker.
 *
 * Drains audit_job_queue and runs each job through runAudit() (deterministic
 * engine + optional Fireworks AI + atomic commit). This is the durable
 * execution side of the Phase 9 architecture: the HTTP run route only
 * enqueues; an audit survives the request ending because the queue is a
 * Postgres table and this function processes it independently.
 *
 * Deployment: `supabase functions deploy audit-worker` (or the dashboard).
 * Invocation: scheduled (Supabase scheduled function, every ~30s–60s) OR
 *   triggered directly after enqueue via an authenticated fetch to this
 *   function's URL with the service-role key as the bearer token. Both are
 *   safe: the function only ever dequeues jobs that were authorized at enqueue
 *   time, and runAudit refuses to re-execute already-running/completed audits.
 *
 * Secrets (server-side only, read from the function's environment):
 *   - SUPABASE_URL / NEXT_PUBLIC_SUPABASE_URL
 *   - SUPABASE_SERVICE_ROLE_KEY
 *   - FIREWORKS_API_KEY (optional — absent ⇒ deterministic-only audits)
 *
 * This file is Deno-entry code. The actual queue-drain logic lives in the
 * bundled artifact at ./_worker.bundle.js, produced by
 * scripts/phase9/build-worker.mjs (esbuild). The bundle replaces the
 * `server-only` import and Node-only logger with Deno-safe shims so the same
 * src/lib/audit-queue/worker.ts core is shared with the Node dev worker.
 *
 * No secrets, source code, or provider responses are logged. Payloads in the
 * queue contain only the audit id.
 */

// The bundle is generated by scripts/phase9/build-worker.mjs and resolved at
// deploy/build time; this Deno entry is typechecked by Deno, not Next's tsc.
import { processQueueBatch, createAuditQueueClient, createSupabaseAuditRepository } from "./_worker.bundle.js";

const SUPABASE_URL =
  Deno.env.get("SUPABASE_URL") ?? Deno.env.get("NEXT_PUBLIC_SUPABASE_URL") ?? "";
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

function json(body: unknown, status = 200, extraHeaders: Record<string, string> = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...extraHeaders },
  });
}

Deno.serve(async (req: Request) => {
  // Authenticated/internal invocation: require a service-role bearer token so
  // arbitrary users cannot drive the worker. The Supabase scheduled-function
  // invoker passes this automatically; a manual curl must include it.
  const auth = req.headers.get("authorization") ?? "";
  const expected = `Bearer ${SERVICE_ROLE_KEY}`;
  if (!SERVICE_ROLE_KEY || auth !== expected) {
    return json({ ok: false, error: "unauthorized" }, 401);
  }

  if (!SUPABASE_URL) {
    return json({ ok: false, error: "misconfigured" }, 500);
  }

  const workerId = crypto.randomUUID();
  const queue = createAuditQueueClient({
    supabaseUrl: SUPABASE_URL,
    serviceRoleKey: SERVICE_ROLE_KEY,
  });
  const repository = createSupabaseAuditRepository({
    supabaseUrl: SUPABASE_URL,
    serviceRoleKey: SERVICE_ROLE_KEY,
  });

  const started = Date.now();
  try {
    const result = await processQueueBatch({
      workerId,
      queue,
      repository,
      aiDeps: undefined, // resolve Fireworks lazily inside runAudit
      maxJobsPerBatch: 10,
    });
    return json({ ok: true, ...result, durationMs: Date.now() - started });
  } catch (err) {
    console.error(JSON.stringify({
      ts: new Date().toISOString(),
      level: "error",
      event: "worker.batch_crashed",
      workerId,
      error: err instanceof Error ? err.message : "unknown",
      durationMs: Date.now() - started,
    }));
    return json({ ok: false, error: "worker_failed" }, 500);
  }
});
